apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: icr-pipeline
spec:
  description: >-
    This is an integration pipeline example
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      type: string
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'


    - description: 'Namespace where the application is running'
      name: NAMESPACE
      type: string
      default: "default"

    - name: icr-scan
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/jaintapauljp/k8s-integration
          - name: revision
            value: master
          - name: pathInRepo
            value: icr-scan.yaml

      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)

        - name: NAMESPACE
          value: $(params.NAMESPACE)